spring:
  application:
    name: barber-shop-api
  datasource:
    url: ${{ Postgres.DATABASE_URL }}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate